mod category_checker;
mod compile_time_constant_checker;
mod context;
mod mutability_checker;
mod name_resolver;
mod phase;
mod phase_executor;
mod phase_graph;
mod result;
mod scope;
mod semantic_analyzer;
mod symbol;
mod symbol_table;
mod type_checker;
mod types;

pub(crate) use phase_graph::PhaseGraph;
pub(crate) use result::SemanticResult;
pub(crate) use semantic_analyzer::SemanticAnalyzer;
pub(crate) use types::Type;
